import { NextResponse } from "next/server";

export const runtime = "nodejs";

/**
 * Optional LLM upgrade for the AI instructor. If ANTHROPIC_API_KEY is set the
 * instructor's free-form answers are generated by Claude, grounded in the
 * current specimen context. Without a key it returns `{ fallback: true }` and
 * the client uses its local grounded answer — the feature never breaks.
 */
export async function POST(req: Request) {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return NextResponse.json({ fallback: true });

  let body: {
    question?: string;
    practical?: string;
    selected?: string | null;
    mode?: string;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ fallback: true });
  }

  const system = `You are the AI Laboratory Instructor inside Biology Entelloq, a virtual biology lab. You stand beside a student performing a hands-on practical. Be a warm, precise professor: concise (2–4 sentences), scientifically accurate, and encouraging. Never mention that you are an AI model.

Specimen context: ${body.practical ?? "a biological specimen"}.
Current mode: ${body.mode ?? "explore"}.
${body.selected ? `The student currently has the ${body.selected} selected.` : ""}`;

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: "claude-sonnet-5",
        max_tokens: 400,
        system,
        messages: [
          { role: "user", content: body.question ?? "Explain this specimen." },
        ],
      }),
    });
    if (!res.ok) return NextResponse.json({ fallback: true });
    const data = (await res.json()) as {
      content?: { type: string; text?: string }[];
    };
    const answer = data.content?.find((c) => c.type === "text")?.text;
    if (!answer) return NextResponse.json({ fallback: true });
    return NextResponse.json({ answer });
  } catch {
    return NextResponse.json({ fallback: true });
  }
}
