/*
 * data.js — the knowledge behind every scale.
 *
 * The stage files own the VISUALS; this file owns the MEANING. Each of the
 * thirteen scales carries: what it is, its physical size, a one-line orientation,
 * a few real facts, the interactive hotspots (each with a name + explanation, and
 * where relevant a disease it underlies), plus research, labs, related concepts
 * and a seed question for the AI. `UNI_ORDER` is the zoom axis, Universe → Atom.
 *
 * Model notes distinguish established structure from illustrative geometry,
 * motion and scale choices; source links support the detailed descriptions.
 */

const UNI_ORDER = [
  'universe', 'earth', 'biome', 'ecosystem', 'organism',
  'organ', 'tissue', 'cell', 'organelle', 'protein',
  'dna', 'nucleotide', 'atom',
];
UNI.ORDER = UNI_ORDER;

const UNI_DATA = {
  universe: {
    title: 'The Universe', size: '~10²⁶ m', scaleLabel: 'observable universe',
    blurb: 'Life belongs to a cosmic history. Much of its hydrogen dates to the early universe; heavier elements were assembled through stellar processes. On Earth, those ingredients became living chemistry.',
    facts: [
      'The observable universe contains an immense number of galaxies; estimates depend on how faint a population is counted.',
      'The elements of life — carbon, oxygen, nitrogen — were made inside dying stars.',
      'You are, quite literally, a way for the universe to know itself.',
    ],
    hotspots: {
      milkyway: { name: 'A Spiral Galaxy', desc: 'A Hubble spiral-galaxy photograph gives context for our home galaxy. It is not an exterior photograph of the Milky Way.' },
      elements: { name: 'Stardust', desc: 'Supernovae seeded space with carbon, oxygen and iron. Biology is what those ashes did next.' },
    },
    research: ['Astrobiology: the search for biosignatures on exoplanets'],
    labs: [],
    related: ['earth', 'atom'], ai: 'Why is carbon the backbone of all known life?',
    modelNote: 'A composed astronomical scene using archived Hubble imagery. Placement, parallax and zoom are illustrative, not a three-dimensional survey or a view of the entire universe.',
  },
  earth: {
    title: 'Earth', size: '~10⁷ m', scaleLabel: 'a living planet',
    blurb: 'A thin film of life wraps a ball of rock — the biosphere. For 3.8 billion years it has been rewriting the planet, oxygenating the air and painting the continents green.',
    facts: [
      'Life strongly influences Earth’s atmosphere, especially its oxygen and carbon cycles.',
      'Photosynthesis put the oxygen in the air; before life, there was almost none.',
      'The biosphere is astonishingly thin — most life lives within a few km of the surface.',
    ],
    hotspots: {
      atmosphere: { name: 'The Atmosphere', desc: '21% oxygen — a signature of life. Cyanobacteria and plants exhale it; you breathe their exhaust.' },
      oceans: { name: 'The Oceans', desc: 'Marine microbes play major roles in photosynthesis and food webs. The exact environment in which life first arose remains an open question.' },
      land: { name: 'The Continents', desc: 'Green with forests and grasslands — vast solar collectors turning light into living carbon.' },
    },
    research: ['Earth-system science: life as a planetary force'],
    labs: [],
    related: ['biome', 'universe'], ai: 'How did life change Earth’s atmosphere?',
    modelNote: 'A globe using archived NASA day/night maps with illustrative clouds and atmosphere. This is not current weather, live satellite imagery or a climate simulation.',
  },
  biome: {
    title: 'A Biome', size: '~10⁵ m', scaleLabel: 'climate & community',
    blurb: 'Zoom in and the green resolves into biomes — rainforest, savanna, tundra — each a community of life shaped by climate, and each a machine for moving carbon and water.',
    facts: [
      'Tropical rainforests hold over half of all land species on ~6% of the land.',
      'A biome is defined by its climate and dominant plant life, not by geography.',
      'Forests move water: much of the rain over the Amazon is exhaled by the trees themselves.',
    ],
    hotspots: {
      canopy: { name: 'The Canopy', desc: 'The forest’s sunlit roof — the most biodiverse layer, a city of leaves, insects and birds.' },
      soil: { name: 'The Soil', desc: 'A living skin: fungal networks and microbes recycle the dead back into the living.' },
      water: { name: 'The Water Cycle', desc: 'Transpiration lifts water from root to leaf to sky — biology driving weather.' },
      roots: { name: 'Roots & Root Flares', desc: 'Roots anchor trees and absorb water and mineral nutrients. These visible root flares indicate connections to a much larger underground system that is not fully modelled.' },
      understory: { name: 'Understory', desc: 'Low plants grow beneath the canopy in reduced light. This diorama includes small frond-like plants to distinguish the understory from the taller trees.' },
      litter: { name: 'Leaf Litter', desc: 'Fallen leaves cover the forest floor. Decomposers break this material down, returning nutrients to soil and releasing carbon through respiration.' },
    },
    diseases: ['Deforestation & zoonotic spillover — new diseases crossing from wildlife'],
    research: ['Biodiversity & ecosystem stability'],
    labs: [],
    related: ['ecosystem', 'earth'], ai: 'Why are rainforests so biodiverse?',
    modelNote: 'A constructed forest patch represents canopy, understory, roots, leaf litter and water. Trees and terrain are illustrative, not a scanned forest or a biome at literal scale.',
  },
  ecosystem: {
    title: 'An Ecosystem', size: '~10³ m', scaleLabel: 'the web of life',
    blurb: 'Inside a biome, energy flows through a web — sun to plant to herbivore to predator — and matter cycles endlessly. Pull one thread and the whole web shivers.',
    facts: [
      'Energy transfer between trophic levels is inefficient and varies among ecosystems; 10% is a useful approximation, not a fixed law.',
      'Most food webs are powered by photosynthesis; some begin with chemosynthesis.',
      'Energy flows through a web while nutrients can be recycled.',
    ],
    hotspots: {
      producer: { name: 'Producers', desc: 'The plant represents photosynthetic producers, which convert light energy into chemical energy.' },
      herbivore: { name: 'Herbivores', desc: 'The caterpillar represents a primary consumer that feeds on plant material.' },
      predator: { name: 'Predators', desc: 'The spider represents a consumer of other animals; it does not receive a direct feeding link from the plant.' },
      decomposer: { name: 'Decomposers', desc: 'Fungi and bacteria that return the dead to the soil, closing the loop of matter.' },
    },
    diseases: ['Trophic collapse when a keystone species is lost'],
    research: ['Food-web ecology & rewilding'],
    labs: ['Predator & prey — the Lotka-Volterra bench'],
    related: ['organism', 'biome'], ai: 'What is a keystone species?',
    modelNote: 'A simplified food web, not a measured community. Organisms are not to scale. Green paths carry food energy; the ochre return path represents recycled nutrients, not recycled energy.',
    source: {label:'Energy flow · OpenStax Biology',url:'https://openstax.org/books/biology-2e/pages/46-2-energy-flow-through-ecosystems'},
  },
  organism: {
    title: 'An Organism', size: '~10⁰ m', scaleLabel: 'a single life',
    blurb: 'One node in the web is one life — trillions of cells cooperating as a single self. Every organ, every heartbeat, is that colony keeping itself alive.',
    facts: [
      'The human body contains trillions of cells; totals vary with body size and the counting method.',
      'Most nucleated body cells share a genome, yet gene activity produces very different cell types. Mature red blood cells lack a nucleus.',
      'Cell turnover varies greatly: some epithelia renew rapidly, while many neurons persist for decades.',
    ],
    hotspots: {
      nervous: { name: 'Brain & Nervous System', desc: 'The two cerebral hemispheres, cerebellum and brainstem coordinate sensing, movement and internal regulation. This view shows selected structures, not every nerve.' },
      circulatory: { name: 'Heart & Circulation', desc: 'The heart drives pulmonary and systemic circulation. The highlighted pump lies between the lungs, with its apex directed toward the subject’s left.' },
      skeleton: { name: 'The Skeleton', desc: 'A simplified axial and limb scaffold supports the body and protects organs. Bone is living tissue; marrow in selected bones produces blood cells.' },
      lungs: { name: 'Lungs & Bronchi', desc: 'The trachea divides into two principal bronchi. The right lung has three lobes and the left two; fissures indicate their boundaries in this simplified model.' },
      liver: { name: 'Liver', desc: 'The liver occupies mainly the right upper abdomen, beneath the diaphragm. It processes absorbed nutrients, produces bile and performs many metabolic functions.' },
      stomach: { name: 'Stomach', desc: 'The J-shaped stomach receives the oesophagus in the left upper abdomen and empties through the pylorus into the duodenum.' },
      intestine: { name: 'Small Intestine', desc: 'The duodenum leads into folded jejunum and ileum. This connected teaching path represents digestion and absorption, not the exact arrangement of an individual person’s loops.' },
      colon: { name: 'Large Intestine', desc: 'Ascending, transverse and descending portions frame the small intestine; the sigmoid region continues toward the rectum. The colon absorbs water and electrolytes.' },
      ribcage: { name: 'Ribs & Costal Cartilage', desc: 'Twelve pairs of ribs protect the thorax. The first seven pairs connect to the sternum through their own cartilage; the last two pairs have no anterior attachment.' },
      aorta: { name: 'Aortic Arch', desc: 'The aorta carries blood from the left ventricle into systemic circulation. Its arch turns posteriorly into the descending aorta; small branches are simplified here.' },
    },
    diseases: ['Systemic disease — when one system’s failure cascades through the whole body'],
    research: ['Systems physiology & whole-body simulation'],
    labs: ['Explore a virtual specimen in the Dissection Lab'],
    related: ['organ', 'ecosystem'], ai: 'How do 37 trillion cells act as one organism?',
    modelNote: 'An illustrative human systems model, not a patient scan. The translucent body exposes selected skeleton, vessels and organs; tissue thicknesses and vessel calibres are simplified.',
  },
  organ: {
    title: 'The Heart', size: '~10⁻¹ m', scaleLabel: 'an organ at work',
    blurb: 'Zoom into the chest and meet the hardest-working muscle you own — a fist-sized pump that beats ~100,000 times a day, moving your entire blood volume every minute.',
    facts: [
      'Contraction alternates with relaxation, allowing the chambers to fill between beats.',
      'Its own pacemaker — the SA node — fires the rhythm; it needs no signal from the brain to beat.',
      'The left ventricle’s wall is thickest because it pumps blood to the entire body.',
    ],
    hotspots: {
      atrium: { name: 'Right Atrium', desc: 'The right atrium receives systemic venous blood through the superior and inferior venae cavae, before passing it to the right ventricle.' },
      ventricle: { name: 'Ventricles', desc: 'The pumping chambers. The left ventricle drives blood through the whole body.' },
      valve: { name: 'Valves (Internal)', desc: 'Heart valves prevent backflow. They lie inside the chambers and vessel roots, so this external model indicates their location without pretending to expose their leaflets.' },
      coronary: { name: 'Coronary Arteries', desc: 'The heart’s own supply lines. Block one and the muscle downstream begins to die.' },
      leftAtrium: { name: 'Left Atrium', desc: 'This mainly posterior chamber receives oxygenated blood through the pulmonary veins and passes it through the mitral valve to the left ventricle. Orbit to inspect its position.' },
      auricle: { name: 'Left Auricle', desc: 'The ear-shaped muscular appendage extends from the left atrium. It is an external landmark, not a separate pumping chamber.' },
      aorta: { name: 'Aorta & Arch Branches', desc: 'The aorta leaves the left ventricle. Three arch branches supply the head, neck and upper limbs; the arch continues into the descending aorta.' },
      pulmonary: { name: 'Pulmonary Trunk', desc: 'The pulmonary trunk leaves the right ventricle and divides into left and right pulmonary arteries. Unlike systemic arteries, these carry relatively deoxygenated blood.' },
      superiorCava: { name: 'Superior Vena Cava', desc: 'The superior vena cava returns blood from the upper body to the right atrium. The cut end is shown as an open vessel lumen.' },
      inferiorCava: { name: 'Inferior Vena Cava', desc: 'The inferior vena cava returns blood from below the diaphragm to the right atrium. Rotate the model to inspect its inferior, posterior approach.' },
      pulmonaryVeins: { name: 'Pulmonary Veins', desc: 'Usually four pulmonary veins bring oxygenated blood from the lungs into the posterior left atrium. Their short exterior segments are simplified here.' },
    },
    diseases: ['Myocardial infarction (heart attack)', 'Arrhythmia', 'Heart failure'],
    research: ['Cardiac regeneration & lab-grown heart tissue'],
    labs: ['Dissect the heart in the Dissection Lab'],
    related: ['tissue', 'organism'], ai: 'How does the heart beat without the brain telling it to?',
    modelNote: 'An illustrative external human heart with surface coronary vessels and connected great vessels. Valve interiors are not exposed; colour and contraction are explanatory, not a diagnostic simulation.',
    source: {label:'Heart anatomy · OpenStax',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/19-1-heart-anatomy'},
  },
  tissue: {
    title: 'Cardiac Tissue', size: '~10⁻³ m', scaleLabel: 'cells, organised',
    blurb: 'The heart wall resolves into tissue — sheets of muscle cells wired together so tightly that they beat as one. This is where the pump becomes a crowd.',
    facts: [
      'Cardiac muscle cells are joined by intercalated discs that let the signal to contract leap cell-to-cell.',
      'The cells are striped (striated) because their contractile proteins line up in perfect ranks.',
      'Tissues contain specialised cells and extracellular material organised for related functions.',
    ],
    hotspots: {
      cardiomyocyte: { name: 'Cardiomyocyte', desc: 'A branching, striated heart-muscle cell with abundant mitochondria. It depends on a continuous oxygen and nutrient supply to sustain contraction.' },
      disc: { name: 'Intercalated Disc', desc: 'The electrical handshake between cells that lets a whole sheet contract in unison.' },
      capillary: { name: 'Capillary', desc: 'A vessel one cell wide — where oxygen finally leaves the blood and enters the tissue.' },
      nucleus: { name: 'Central Nucleus', desc: 'Cardiomyocytes usually have one central nucleus, sometimes two. These exposed nuclei are teaching cutaways, not nuclei naturally sitting on the cell surface.' },
      striation: { name: 'Striations', desc: 'Repeated arrangements of actin and myosin within sarcomeres produce the striped appearance. The visible band spacing is enlarged for explanation.' },
      branch: { name: 'Branching Cell Network', desc: 'Cardiac muscle cells branch and join neighbours, forming an interconnected network. Intercalated discs provide mechanical and electrical connections.' },
      erythrocyte: { name: 'Red Blood Cell', desc: 'Biconcave erythrocytes transport oxygen in haemoglobin through narrow capillaries. Their movement here illustrates perfusion; it is not a measured flow simulation.' },
    },
    diseases: ['Fibrosis — scar tissue that can’t contract', 'Cardiomyopathy'],
    research: ['Tissue engineering & organs-on-a-chip'],
    labs: ['Explore tissue sections in the virtual microscope'],
    related: ['cell', 'organ'], ai: 'Why is heart muscle striated?',
    modelNote: 'Illustrative branching cardiomyocytes, intercalated discs and capillary. Nuclei are exposed as teaching cutaways. Striation spacing, colour and rhythmic motion are not calibrated microscopy.',
    source: {label:'Cardiac muscle tissue · OpenStax',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/10-7-cardiac-muscle-tissue'},
  },
  cell: {
    title: 'The Cell', size: '~10⁻⁵ m', scaleLabel: 'the unit of life',
    blurb: 'Explore an opened animal cell: a double nuclear envelope encloses chromatin, membrane sheets prepare proteins, and interconnected compartments organize living chemistry.',
    facts: [
      'A typical nucleated diploid human cell contains about two metres of DNA. Mature red blood cells are an important exception: they have no nucleus.',
      'The outer nuclear membrane is continuous with the endoplasmic reticulum; its pores regulate exchange with the cytoplasm.',
      'Animal cells vary widely in shape and organelle number. This composite model shows selected structures, not a specific measured cell.',
    ],
    hotspots: {
      membrane: { name: 'Cell Membrane', desc: 'A phospholipid bilayer with membrane proteins separates the cell from its surroundings and regulates exchange. The opening here is an educational cutaway.' },
      nucleus: { name: 'Nucleus', desc: 'The nucleus houses most of an animal cell’s DNA. Its opened double envelope reveals interphase chromatin and the nucleolus inside.' },
      mito: { name: 'Mitochondrion', desc: 'Its inner membrane couples electron transport to ATP production. This model does not depict literal sparks of energy.' },
      er: { name: 'Rough Endoplasmic Reticulum', desc: 'Membrane sheets continuous with the nuclear envelope carry ribosomes that synthesize many secreted and membrane proteins.' },
      golgi: { name: 'Golgi Apparatus', desc: 'A stack of flattened membrane sacs modifies and sorts proteins and lipids. Transport vesicles carry material between the ER, Golgi and other destinations.' },
      ribosome: { name: 'Ribosomes', desc: 'Machines that read mRNA and build proteins, one amino acid at a time.' },
      nucleolus: { name: 'Nucleolus', desc: 'This region inside the nucleus assembles ribosomal subunits around ribosomal RNA. It is not enclosed by its own membrane.' },
      pores: { name: 'Nuclear Pores', desc: 'Protein complexes spanning the nuclear envelope regulate exchange between nucleus and cytoplasm. The openings are enlarged here for inspection.' },
      lyso: { name: 'Lysosome', desc: 'A membrane-bound compartment whose acidic interior contains enzymes that break down and recycle material.' },
      cytoskeleton: { name: 'Cytoskeleton', desc: 'A selected network of structural fibres supports cell shape and intracellular transport. A living cell contains many more dynamically reorganizing filaments.' },
      ser: { name: 'Smooth Endoplasmic Reticulum', desc: 'Interconnected membrane tubules without attached ribosomes participate in lipid synthesis and calcium storage; their roles vary with cell type.' },
      chromatin: { name: 'Chromatin', desc: 'DNA and associated proteins form chromatin. These selected strands represent the dispersed material of an interphase nucleus, not condensed dividing chromosomes or a traced genome.' },
      envelope: { name: 'Nuclear Envelope', desc: 'Two membranes surround the nucleus. The space between them is continuous with the ER lumen, and the outer membrane joins the ER membrane.' },
      vesicle: { name: 'Transport Vesicle', desc: 'Small membrane-bound carriers move selected cargo between cellular compartments. These carriers beside the Golgi illustrate transport, without depicting measured trafficking rates.' },
      centrosome: { name: 'Centrosome', desc: 'A major microtubule-organizing centre in many animal cells contains a pair of centrioles. The simplified cylinders indicate ninefold organization; their protein architecture is not resolved here.' },
    },
    diseases: ['Cancer — a cell that forgets to stop dividing', 'Mitochondrial disease'],
    research: ['Single-cell sequencing & the Human Cell Atlas'],
    labs: [],
    related: ['organelle', 'tissue', 'dna'], ai: 'What makes a cell alive rather than just chemistry?',
    modelNote: 'An illustrative animal-cell cutaway, not a complete cell atlas or an electron micrograph. Colours, counts, sizes and spacing make selected compartments legible; membrane openings expose normally hidden structures.',
    source: {label:'Eukaryotic cells · OpenStax Biology',url:'https://openstax.org/books/biology-2e/pages/4-3-eukaryotic-cells'},
  },
  organelle: {
    title: 'The Mitochondrion', size: '~10⁻⁶ m', scaleLabel: 'the cell’s power plant',
    blurb: 'An opened mitochondrion reveals two membranes, connected cristae, matrix-facing ATP synthase and a small circular genome. Its inner membrane couples electron transport to ATP synthesis.',
    facts: [
      'Mitochondria descend from a bacterial endosymbiont. Their genomes encode only a small fraction of the proteins they need.',
      'Cristae are continuous folds of the inner membrane. Their interiors connect to the intermembrane space.',
      'Human mitochondrial DNA is normally inherited maternally; most mitochondrial proteins are encoded in nuclear DNA.',
    ],
    hotspots: {
      cristae: { name: 'Cristae', desc: 'Folds of one continuous inner membrane increase its area and organize respiratory machinery. The connected sheets shown here simplify the varied crista shapes found in living cells.' },
      matrix: { name: 'Matrix', desc: 'The compartment enclosed by the inner membrane contains enzymes of the citric acid cycle, mitochondrial DNA and mitochondrial ribosomes.' },
      atpsynthase: { name: 'ATP Synthase', desc: 'Protons returning from the intermembrane space to the matrix drive this enzyme. Its catalytic head faces the matrix, where ADP and phosphate are used to make ATP.' },
      mtdna: { name: 'Mitochondrial DNA', desc: 'Human mitochondrial DNA is a circular genome packaged with proteins into nucleoids. The unknotted loop here is a simplified circular path, not an atomic DNA structure.' },
      outer: { name: 'Outer Membrane', desc: 'The organelle’s outer boundary contains channels that allow many small molecules into the intermembrane space.' },
      inner: { name: 'Inner Membrane', desc: 'A selective membrane surrounding the matrix. Its boundary continues into the cristae and contains respiratory-chain complexes and ATP synthase.' },
      interspace: { name: 'Intermembrane Space', desc: 'The narrow compartment between the membranes is continuous with the interiors of the cristae. Electron transport pumps protons here from the matrix.' },
      ribosome: { name: 'Mitochondrial Ribosome', desc: 'Mitochondrial ribosomes translate the small set of proteins encoded by mitochondrial DNA. Most mitochondrial proteins instead arrive from the cytoplasm.' },
    },
    diseases: ['Mitochondrial myopathies', 'Roles in ageing & neurodegeneration'],
    research: ['Mitochondrial replacement therapy'],
    labs: ['Cellular Respiration — a six-lens lesson with a live ATP tally'],
    related: ['protein', 'cell'], ai: 'How does a mitochondrion actually make ATP?',
    modelNote: 'An illustrative animal mitochondrion with an opened outer wall and continuous inner-membrane folds. Protein machinery is enlarged and simplified; colours, molecule counts and motion are not physically calibrated.',
    source: {label:'Mitochondria · The Cell · NCBI Bookshelf',url:'https://www.ncbi.nlm.nih.gov/books/NBK9896/'},
  },
  protein: {
    title: 'Haemoglobin', size: '~10⁻⁸ m', scaleLabel: 'four chains, one protein',
    blurb: 'Human deoxyhaemoglobin, shown from deposited experimental coordinates: four folded globin chains with a heme in each. Explore the actual fold rather than a generic protein symbol.',
    facts: ['Two alpha and two beta chains make this tetramer.', 'This deposited structure contains 574 amino-acid residues and four hemes.', '4HHB is the deoxygenated form; no bound oxygen is shown.'],
    hotspots: {
      helix: {name:'Globin Fold',desc:'Follow one continuous amino-acid backbone through its compact, mostly helical fold. The trace passes through deposited C-alpha positions.'},
      sheet: {name:'Four Subunits',desc:'The four colours separate chains A, B, C and D. The chains associate into one tetramer; the colours are a visual key, not a natural pigment.'},
      heme: {name:'Heme',desc:'Each globin pocket contains a porphyrin group surrounding an iron atom. Here its heavy atoms and deposited connectivity are displayed.'},
      active: {name:'Deoxygenated Heme',desc:'Iron is highlighted within the heme. This 4HHB snapshot is deoxygenated, not an animation of oxygen binding.'},
    },
    diseases:['Sickle-cell disease involves an altered beta-globin sequence'],
    research:['Experimental structural biology and protein prediction'],
    labs:[],related:['dna','organelle'],ai:'How do haemoglobin’s four subunits work together?',
    modelNote:'Coordinate-derived C-alpha traces and heme heavy atoms, PDB 4HHB. Side chains, solvent, hydrogens and molecular motion are omitted; atom radii and colours are illustrative.',
    source:{label:'Fermi et al. · 4HHB · RCSB PDB',url:'https://www.rcsb.org/structure/4HHB'},
  },
  dna: {
    title:'DNA',size:'~4 × 10⁻⁹ m',scaleLabel:'a measured molecular fragment',
    blurb:'A complete 12-base-pair DNA duplex, reconstructed from the 1BNA crystal structure. The two continuous backbones wind around stacked complementary base pairs.',
    facts:['Both strands contain the sequence CGCGAATTCGCG and run in opposite directions.', 'This short duplex is slightly bent, not an ideal mathematical spiral.', 'Its 24 nucleotides include both A–T and G–C pairs.'],
    hotspots:{
      helix:{name:'B-DNA Duplex',desc:'The actual deposited fragment forms a right-handed double helix. Local twist and groove geometry vary along its length.'},
      basepair:{name:'Base Pair',desc:'Complementary A–T and G–C bases face inward. Fine dashed links indicate hydrogen bonds; solid sticks indicate covalent connections.'},
      backbone:{name:'Sugar–Phosphate Backbone',desc:'Each continuous outer path follows connected sugar and phosphate atoms. The two strands have opposite chemical direction.'},
      gene:{name:'DNA Fragment',desc:'These 12 base pairs are a structural sample, not a complete gene. Genes can encode functional RNAs, including RNAs translated into proteins.'},
    },
    diseases:['Mutations and DNA repair disorders'],research:['DNA structure and sequence-dependent bending'],
    labs:['DNA Replication — leading and lagging strands'],related:['nucleotide','protein'],ai:'Why do DNA strands run in opposite directions?',
    modelNote:'Heavy-atom model of PDB 1BNA, 12 base pairs. Atom sizes, sticks and backbone emphasis are display choices; hydrogens, water and bond orders are omitted.',
    source:{label:'Drew et al. · 1BNA · RCSB PDB',url:'https://www.rcsb.org/structure/1BNA'},
  },
  nucleotide: {
    title:'An A–T Base Pair',size:'~10⁻⁹ m',scaleLabel:'two complementary nucleotides',
    blurb:'Adenine and thymine from the same DNA structure, enlarged to reveal their complete heavy-atom framework. Follow the base, five-membered sugar ring and phosphate on each side.',
    facts:['A nucleotide contains a base, sugar and phosphate.', 'Adenine has fused six- and five-membered rings; thymine has one six-membered ring.', 'Two dashed contacts mark the A–T hydrogen bonds.'],
    hotspots:{
      base:{name:'Adenine & Thymine',desc:'The fused adenine rings pair with the single thymine ring. Carbon is grey, nitrogen blue, oxygen terracotta and phosphorus ochre.'},
      sugar:{name:'Deoxyribose',desc:'The five-membered ring has four carbon atoms and one oxygen. Its fifth carbon lies outside the ring, connecting toward the phosphate.'},
      phosphate:{name:'Phosphate',desc:'Phosphate links neighbouring nucleotides in a DNA strand. The displayed residues are extracted fragments, so their outer backbone connections end here.'},
      hbond:{name:'Hydrogen Bonds',desc:'The dashed lines mark two base-pair contacts. They are distinct from the solid covalent framework; individual hydrogens are not displayed.'},
    },
    research:['Molecular recognition and DNA chemistry'],labs:['DNA Replication — watch the fork run'],
    related:['atom','dna'],ai:'How does the geometry of A and T make a complementary pair?',
    modelNote:'Residues A6 and B19 extracted from PDB 1BNA. A rigid rotation preserves their experimental coordinates; hydrogens and bond orders are omitted.',
    source:{label:'1BNA coordinates · RCSB PDB',url:'https://www.rcsb.org/structure/1BNA'},
  },
  atom: {
    title:'A Carbon Atom',size:'~10⁻¹⁰ m',scaleLabel:'probability, not planetary orbits',
    blurb:'Carbon has six electrons. Their behaviour is described by quantum states, not tiny planets circling a nucleus. These stationary clouds illustrate that distinction.',
    facts:['The neutral ground-state configuration is 1s² 2s² 2p².', 'The outer 2s and 2p electrons participate in carbon’s chemistry.', 'Carbon-12 has six protons and six neutrons in its nucleus.'],
    hotspots:{
      nucleus:{name:'Carbon-12 Nucleus',desc:'Six protons and six neutrons. The nucleus is enlarged enormously relative to the clouds so it remains visible.'},
      electron:{name:'Illustrative Electron Clouds',desc:'Dots suggest probability density; they are not individual electrons, measured positions or trajectories. Cloud shapes here are qualitative.'},
      valence:{name:'Valence States',desc:'The outer 2s and 2p states hold four electrons in an isolated neutral carbon atom. Molecular bonding changes their distribution.'},
    },
    research:['Atomic spectroscopy and electronic structure'],
    labs:[],related:['nucleotide','universe'],ai:'Why is an electron cloud different from an orbit?',
    modelNote:'Qualitative s/p cloud illustration, not a solved or measured carbon wavefunction. Dot counts are aesthetic samples; the nucleus and clouds are not drawn to one scale.',
    source:{label:'Carbon atomic data · NIST',url:'https://physics.nist.gov/PhysRefData/Handbook/Tables/carbontable1.htm'},
  },
};
